### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by DenisArsenev** [oleg-golovanov/pyshtrih#12]
Пожалуйста, сделайте нормальную документацию с (!!!) примерами кода и подключения. Или хотя бы ещё пару тестовых примеров кода. Тот единственный пример из описания не работает и его недостаточно. Классная идея, классный и нужный драйвер - напишите пару примеров, чтобы гораздо больше людей разобрались, как им пользоваться

**Comment by oleg-golovanov** [comment]
А что не работает в примере из README? Замечу, что он написан на python2.
Примеры чего вы хотели бы видеть в документации?

**Comment by Uffik81** [comment]
Доброе, думаю добавить пример расчета и внесения 1162 тэга в чек, будет достаточно.

**Comment by DenisArsenev** [comment]
Обычно пример из read.me работает сразу "из коробки". С примером из read.me pyshtrih пришлось посидеть пол дня, чтобы он заработал.
По поводу того, что хотелось бы видеть в примере:
Код вашего примера является устаревшим и не соответствует сегодняшним требованиям ОФД к формату фискальных документов. Для того, чтобы это исправить, нужно дополнить пример операции продажи внесением обязательных тегов, хотя бы одного, через метод send_tlv_struct(). Ещё раз: чтобы драйвер был актуален и соответствовал современным требованиям ОФД, необходима возможность добавления тегов. В вашем драйвере возможность добавления тегов реализована, но в примере этого нет. Я пытался самостоятельно разобраться с тем, в каком формате передаются данные в метод send_tlv_struct(), но, потратив уйму времени и перепробовав много разных вариантов, так и не нашёл решения, с которым бы метод заработал. Соответственно, думаю, не я один встретился с данной проблемой при использовании метода send_tlv_struct(). Если учесть, что добавление тегов является обязательным элементом при формировании каждого чека по сегодняшнему закону, и есть проблемы с использованием метода добавления тегов в вашем драйвере, хотелось бы видеть пример использования этого метода в примере read.me, чтобы пример соответствовал современным требованиям к фискальным документам и демонстрировал весь типичный процесс операции продажи.

**Comment by oleg-golovanov** [comment]
Могу добавить пример работы с `send_tlv_struct()`, но есть проблема. Набор тэгов очень обширен, а простая работа поддержана только с одним. Поэтому не уверен в необходимости добавления.

По поводу актуальности драйвера - он уже не актуален и таковым скорее всего не будет. Проект под который он писался заморожен.

**Comment by oleg-golovanov** [comment]
#14

**Comment by oleg-golovanov** [comment]
#14 - обсуждение работы с `send_tlv_struct()`.
