### ISSUE TITLE
PaymentItemSign и PaymentTypeSign 

### ISSUE THREAD

**Issue by DenisArsenev** [oleg-golovanov/pyshtrih#13]
Реализована ли в драйвере возможность добавления в чек обязательных на сегодняшний день реквизитов офд - "Признак предмета расчёта" (PaymentItemSign) и "Признак способарасчёта" (PaymentTypeSign)? В оригинальном драйвере Штрих-М эти опции доступны в разделе "Операции ФН"

**Comment by oleg-golovanov** [comment]
Судя по описанию протокола это команда `0xFF46` (Операция V2). Нет, она не поддержана в драйвере.

**Comment by alex-eri** [comment]
> Реализована ли в драйвере возможность добавления в чек обязательных на сегодняшний день реквизитов офд - "Признак предмета расчёта" (PaymentItemSign) и "Признак способарасчёта" (PaymentTypeSign)? В оригинальном драйвере Штрих-М эти опции доступны в разделе "Операции ФН"

https://github.com/alex-eri/pyshtrih/blob/c8905ae5d61f446a7d4635c3983dd66d1faa0fd5/pyshtrih/commands.py#L917
